name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

env:
  AZURE_CONTAINER_REGISTRY: nicoledemo.azurecr.io
  
on:
  push:
    branches: [master]
  workflow_dispatch:


permissions:
      contents: read

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{secrets.ACR_USERNAME}}
          # Container registry password
          password: ${{secrets.ACR_PASSWORD}}
          # Container registry server url
          login-server: ${{env.AZURE_CONTAINER_REGISTRY}}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          # tags: <registry server url>/<app name>:<git commit sha>
          tags: ${{env.AZURE_CONTAINER_REGISTRY}}/hello-world-app:${{ github.sha}}
          file: Dockerfile

  deployToAKS:
    permissions:
      actions: read
      contents: read
      id-token: write
  
    runs-on: ubuntu-latest
    needs: [buildImage]
    environment: Production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Log in with Azure Credentials
      - name: Azure Login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1
        with:
          kubelogin-version: v0.0.25

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          # Resource Group Name
          resource-group: github-action-rg
          # AKS Cluster Name
          cluster-name: nicolek8sdemo
          # AKS Cluster Subscription
          subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Get cluster admin credentials. Values: true or false
          admin: false
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: true
      
      # Substitute environment variables in a file
      - name: envsubst-action
        uses: danielr1996/envsubst-action@1.0.0
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AZURE_CONTAINER_REGISTRY: ${{AZURE_CONTAINER_REGISTRY}}
          CONTAINER_NAME: hello-world-app:${{ github.sha}}
        with:
          input: 
            kubernetes/hello-world-deployment.yaml
          output: 
            hello-world-deployment.yaml
      
      # Deploys application based on given manifest file
      - name: Deploys Application
        uses: Azure/k8s-deploy@v4.9
        with:
          action: deploy
          manifests: |
            hello-world-deployment.yaml
            kubernetes/hello-world-service.yaml
          images: |
            ${{env.AZURE_CONTAINER_REGISTRY}}/hello-world-app:${{ github.sha}}
